version: '3'
services:
  mysql:
    build:
      dockerfile: mysql.dockerfile
      context: .
    image: mysql
    container_name: mysql
    networks: 
      - my-network
    ports:
     - "3306:3306"	
    environment:
     - MYSQL_ROOT_PASSWORD=password  
  phpmyadm:
    build:
      dockerfile: phpmyadm.dockerfile
      context: .
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadm
    ports: 
      - "80:32775"
    networks:
      - my-network
    links:
     - mysql  
    depends_on:
      - "mysql"
networks:
  my-network:
    driver: bridge
